name = "super-selected-microsites"
main = "src/index.js"
compatibility_date = "2026-09-04"

[[routes]]
pattern = "guandu.goodbusiness.cloud"
custom_domain = true

[[routes]]
pattern = "qingyan.goodbusiness.cloud"
custom_domain = true

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
html_handling = "none"
not_found_handling = "none"
